
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =2, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =11, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =12, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =13, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =14, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =15, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =16, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =17, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =18, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =19, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =20, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =21, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =22, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =23, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =24, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =25, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =26, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =27, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =28, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =29, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =30, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =31, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =32, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =33, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =34, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =35, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =36, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =39, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =40, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =43, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =44, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =45, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =46, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =47, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'




-- RENOVACIONES 
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =2,  @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =11, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =12, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =13, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =14, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =15, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =16, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =17, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =18, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =19, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =20, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =21, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =22, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =23, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =24, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =25, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =26, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =27, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =28, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =29, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =30, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =31, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =32, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =33, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =34, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =35, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =36, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =39, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =40, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =43, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =44, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =45, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =46, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =47, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'

-- calculodora de gestion humana. 
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =48, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =48, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'

-- revista construdata
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =49, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =49, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'


EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =41, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=10 Marzo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&TABLASITIOS=<div class="divTable" style="display: table; width: 100%;">          <div class="divTableHeading" style=" background-color: #FFFFFF; display: table-header-group;     font-weight: bold;">          </div>          <div class="divTableBody" style="  display: table-row-group;">           <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="http://Analitica.legis.com.co">  Analitica Jurisprudencial</a>          </div>           </div><br>         <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="http://arancel.legis.com.co">  Arancel Electrónico</a>          </div>           </div><br>         <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="http://www.comunidadcontable.com">  Comunidad contable</a>          </div>           </div><br>         <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="https://www.ambitojuridico.com/">  Ambito Juridico</a>          </div>           </div><br>         <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="https://xperta.legis.co/">  Publicaciones Legis Xperta</a>          </div>           </div><br>                   </div>         </div>&RENOVACION=True&NIT=&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =41, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=10 Marzo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&TABLASITIOS=<div class="divTable" style="display: table; width: 100%;">          <div class="divTableHeading" style=" background-color: #FFFFFF; display: table-header-group;     font-weight: bold;">          </div>          <div class="divTableBody" style="  display: table-row-group;">           <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="http://Analitica.legis.com.co">  Analitica Jurisprudencial</a>          </div>           </div><br>         <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="http://arancel.legis.com.co">  Arancel Electrónico</a>          </div>           </div><br>         <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="http://www.comunidadcontable.com">  Comunidad contable</a>          </div>           </div><br>         <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="https://www.ambitojuridico.com/">  Ambito Juridico</a>          </div>           </div><br>         <div class="divTableRow" style="text-align:center;     display: table-row;">          <div class="divTableCell" style="text-align:center; border: 2px solid #2B00F4; display: table-cell;    padding: 3px 10px; text-decoration: none;">          <a style="text-decoration: none;" href="https://xperta.legis.co/">  Publicaciones Legis Xperta</a>          </div>           </div><br>                   </div>         </div>&RENOVACION=True&NIT=&'








-- silvia premium 
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =50, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =50, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'



EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =51, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =51, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'

EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =52, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =52, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'

EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =53, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=False&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
EXEC [dbo].[InsertaActualizaColaCorreos] @CodTareaEnvioCorreo =53, @CodFilial=6, @Email ='info@legis.com', @QueryString =	'FECHANOTIFICACION=2 mayo de 2025&NOMBRECLIENTE=Usuario Prueba&USUARIOACCESO=info@legis.com&CLAVEACCESO=eNERO23+&PRODUCTO=Prueba&RENOVACION=true&DEMOSTRACION=False&FINALIZACIONDEMO=False&FECHAINICIO=2024-11-29&FECHAFINALIZACION=2025-11-30&NIT=52810666&'
